services:
  back:
      build:
        context: .
        dockerfile: Dockerfile
      image: backend
      container_name: backend
      networks:
        - nv-app
      environment:
        DB_URL:
        JWK_SET_URI:
        ISSUER_URI:
        MG_URI:
        API_KEY:
        USER:
        PASSWORD:
      ports:
        - "8085:8085"
      depends_on:
        - postgres
        - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:8.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: mongo-test
    volumes:
      - mon-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nv-app
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mg_express 
    depends_on:
      - mongodb
    networks:
      - nv-app
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
    ports:
      - '5051:8081'

  pgadmin:
    image: dpage/pgadmin4:snapshot
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nv-app

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nv-app
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL:
      KC_DB_USERNAME:
      KC_DB_PASSWORD:
      KC_BOOTSTRAP_ADMIN_USERNAME:
      KC_BOOTSTRAP_ADMIN_PASSWORD:
      KC_HOSTNAME_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/certs.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/certs.key.pem
    command:
      ["start-dev"]
    volumes:
      - ~/keycloak/certs:/etc/x509/https
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - nv-app
    restart: unless-stopped


volumes:
  mon-data:
  db-data:
  pgadmin:

networks:
  nv-app:
    driver: bridge
