services:
  mongo:
    container_name: mongodb
    image: mongo:8.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: peculiar
      MONGO_INITDB_ROOT_PASSWORD: peculiar
      MONGO_INITDB_DATABASE: mongo-test
    volumes:
      - mon-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nv-app
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    depends_on:
      - mongo
    networks:
      - nv-app
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=peculiar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=peculiar
    ports:
      - '5051:8081'

  pgadmin:
    image: dpage/pgadmin4:snapshot
    environment:
      PGADMIN_DEFAULT_EMAIL: peculiar@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: peculiar
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nv-app

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: nahual_visions
      POSTGRES_USER: peculiar
      POSTGRES_PASSWORD: peculiar
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nv-app
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/nahual_visions
      KC_DB_USERNAME: peculiar
      KC_DB_PASSWORD: peculiar
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      #KC_HTTP_ENABLED: true
      #KC_HOSTNAME: bla.bla.com
      KC_HOSTNAME_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/certs.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/certs.key.pem
    command:
      ["start-dev"]
    volumes:
      - ~/keycloak/certs:/etc/x509/https
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - nv-app
    restart: unless-stopped


volumes:
  mon-data:
  #  me-data:
  db-data:
  pgadmin:

networks:
  nv-app:
    driver: bridge