spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://89.111.170.87:8443/realms/nahual_visions/protocol/openid-connect/certs
          issuer-uri: https://89.111.170.87:8443/realms/nahual_visions/
  data:
    mongodb:
      uri: mongodb://89.111.170.87:27017/nahual-visions
      username: peculiar
      password: peculiar

  datasource:
      url: jdbc:postgresql://89.111.170.87:5432/nahual_visions
      username: peculiar
      driver-class-name: org.postgresql.Driver
      password: peculiar
  liquibase:
    change-log: classpath:db/changelog-master.xml
  ai:
    openai:
      api-key: YOUR_API_KEY

server:
  port: 8085
