spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI} #https://89.111.170.87:8443/realms/nahual_visions/protocol/openid-connect/certs
          issuer-uri: ${ISSUER_URI} #https://89.111.170.87:8443/realms/nahual_visions/
  data:
    mongodb:
      uri: ${MG_URI}}  #mongodb://89.111.170.87:27017/nahual-visions
      username: peculiar
      password: peculiar

  datasource:
      url: ${DB_URL}  #89.111.170.87:5432/nahual_visions
      username: peculiar
      driver-class-name: org.postgresql.Driver
      password: peculiar
  liquibase:
    change-log: classpath:db/changelog-master.xml
  ai:
    openai:
      api-key: ${API_KEY} #YOUR_API_KEY

server:
  port: 8085
